import { Link, router } from '@inertiajs/react';
import type { FormEvent } from 'react';
import { useState } from 'react';
import Pagination from '@/components/admin/pagination';
import AdminLayout from '@/layouts/admin-layout';
import vendorsRoutes from '@/routes/admin/vendors';
import type { Counts, Paginated, Vendor } from '@/types/admin';

export default function VendorsIndex({ vendors, counts }: { vendors: Paginated<Vendor>; counts: Counts }) {
 const params = new URLSearchParams(location.search); const [search, setSearch] = useState(params.get('search') ?? ''); const [status, setStatus] = useState(params.get('status') ?? ''); const submit = (e: FormEvent) => {
 e.preventDefault(); router.get(vendorsRoutes.index.url(), { search, status }, { preserveState: true, replace: true }); 
};

 return <AdminLayout title="Vendor Management" breadcrumb="Vendors"><div className="grid gap-4 sm:grid-cols-4">{Object.entries(counts).map(([label, value]) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-white/10 dark:bg-white/5"><p className="text-sm capitalize text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>)}</div><section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-white/10 dark:bg-white/5"><form onSubmit={submit} className="grid gap-3 border-b border-slate-200 p-5 dark:border-white/10 md:grid-cols-[1fr_12rem_auto]"><input type="search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Business, owner or tax number" className="rounded-xl border border-slate-300 bg-transparent px-4 py-2.5 text-sm dark:border-white/10" /><select value={status} onChange={(e) => setStatus(e.target.value)} className="rounded-xl border border-slate-300 bg-transparent px-4 py-2.5 text-sm dark:border-white/10"><option value="">All statuses</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="suspended">Suspended</option></select><button className="rounded-xl bg-slate-950 px-5 text-sm font-semibold text-white dark:bg-white dark:text-slate-950">Filter</button></form><div className="overflow-x-auto"><table className="min-w-full text-left"><thead className="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-white/5"><tr><th className="px-6 py-3">Business</th><th className="px-5 py-3">Owner</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Applied</th><th className="px-6 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-white/5">{vendors.data.map((vendor) => <tr key={vendor.id}><td className="px-6 py-4"><p className="font-semibold">{vendor.business_name}</p><p className="text-xs text-slate-500">{vendor.business_email}</p></td><td className="px-5 py-4"><p className="text-sm font-medium">{vendor.user.name}</p><p className="text-xs text-slate-500">{vendor.user.email}</p></td><td className="px-5 py-4 text-sm capitalize">{vendor.status}</td><td className="px-5 py-4 text-sm text-slate-500">{new Date(vendor.created_at).toLocaleDateString()}</td><td className="px-6 py-4 text-right"><Link href={vendorsRoutes.show.url(vendor.id)} className="text-sm font-semibold text-indigo-600">Review</Link></td></tr>)}</tbody></table></div><Pagination links={vendors.links} /></section></AdminLayout>; 
}
