<?php

test('admin navigation follows the marketplace module hierarchy', function () {
    $adminLayout = file_get_contents(dirname(__DIR__, 2).'/resources/js/layouts/admin-layout.tsx');

    expect($adminLayout)
        ->toContain("label: 'Dashboard'")
        ->toContain("label: 'Marketplace / Sellers'")
        ->toContain("label: 'Catalogue'")
        ->toContain("label: 'Listings'")
        ->toContain("label: 'Pricing & Offers'")
        ->toContain("label: 'Orders'")
        ->toContain("label: 'Inventory'")
        ->toContain("label: 'Warehouses & Fulfilment'")
        ->toContain("label: 'Logistics'")
        ->toContain("label: 'Returns, RTO & Refunds'")
        ->toContain("label: 'Payments & Settlements'")
        ->toContain("label: 'Customers'")
        ->toContain("label: 'Marketing & Advertising'")
        ->toContain("label: 'Reviews & Questions'")
        ->toContain("label: 'Customer Support'")
        ->toContain("label: 'Reports & Analytics'")
        ->toContain("label: 'Administration'")
        ->toContain("label: 'Today’s Orders'")
        ->toContain("label: 'Gross Merchandise Value'")
        ->toContain("label: 'Net Revenue'")
        ->toContain("label: 'Active Sellers'")
        ->toContain("label: 'Active Customers'")
        ->toContain("label: 'Returns Summary'")
        ->toContain("label: 'Low-stock Alerts'")
        ->toContain("label: 'Fulfilment Performance'")
        ->toContain("label: 'Recent Activities'")
        ->toContain("label: 'All Sellers'")
        ->toContain("label: 'Add Seller'")
        ->toContain("label: 'Seller Applications'")
        ->toContain("label: 'KYC Verification'")
        ->toContain("label: 'Approved Sellers'")
        ->toContain("label: 'Rejected Sellers'")
        ->toContain("label: 'Suspended Sellers'")
        ->toContain("label: 'Seller Documents'")
        ->toContain("label: 'Seller Bank Accounts'")
        ->toContain("label: 'Seller Warehouses'")
        ->toContain("label: 'Seller Performance'")
        ->toContain("label: 'Seller Score'")
        ->toContain("label: 'Seller Violations'")
        ->toContain("label: 'Seller Agreements'")
        ->toContain("label: 'Seller Subscriptions'");
});
