<?php

test('admin navigation follows the marketplace module hierarchy', function () {
    $adminLayout = file_get_contents(dirname(__DIR__, 2).'/resources/js/layouts/admin-layout.tsx');

    expect($adminLayout)
        ->toContain("label: 'Dashboard'")
        ->toContain("label: 'Seller Management'")
        ->toContain("label: 'Catalogue Management'")
        ->toContain("label: 'Pricing & Offers'")
        ->toContain("label: 'Orders'")
        ->toContain("label: 'Inventory'")
        ->toContain("label: 'Warehouses & Fulfilment'")
        ->toContain("label: 'Logistics'")
        ->toContain("label: 'Returns, RTO & Refunds'")
        ->toContain("label: 'Payments & Settlements'")
        ->toContain("label: 'Customers'")
        ->toContain("label: 'Marketing & Advertising'")
        ->toContain("label: 'Reviews & Questions'")
        ->toContain("label: 'Customer Support'")
        ->toContain("label: 'Reports & Analytics'")
        ->toContain("label: 'Administration'")
        ->toContain("label: 'Business Overview'")
        ->toContain("label: 'Today’s Orders'")
        ->toContain("label: 'GMV and Net Revenue'")
        ->toContain("label: 'Active Sellers'")
        ->toContain("label: 'Pending Approvals'")
        ->toContain("label: 'Returns Summary'")
        ->toContain("label: 'Low-stock Alerts'")
        ->toContain("label: 'Fulfilment Performance'")
        ->toContain("label: 'Recent Activities'")
        ->toContain("label: 'All Sellers'")
        ->toContain("label: 'Add Seller'")
        ->toContain("label: 'Seller Applications'")
        ->toContain("label: 'KYC Verification'")
        ->toContain("label: 'Approved / Rejected / Suspended Sellers'")
        ->toContain("label: 'Seller Documents'")
        ->toContain("label: 'Bank Accounts'")
        ->toContain("label: 'Warehouses'")
        ->toContain("label: 'Performance Score'")
        ->toContain("label: 'Violations'")
        ->toContain("label: 'Agreements'")
        ->toContain("label: 'Subscriptions'")
        ->toContain("label: 'All Products'")
        ->toContain("label: 'Add Product'")
        ->toContain("label: 'Listing Requests'")
        ->toContain("label: 'Pending / Approved / Rejected Listings'")
        ->toContain("label: 'Quality Check'")
        ->toContain("label: 'Product Moderation'")
        ->toContain("label: 'Categories'")
        ->toContain("label: 'Brands'")
        ->toContain("label: 'Attributes'")
        ->toContain("label: 'Variants'")
        ->toContain("label: 'Specifications'")
        ->toContain("label: 'Media'")
        ->toContain("label: 'Bundles'")
        ->toContain("label: 'Bulk Upload'")
        ->toContain("label: 'Import / Export'")
        ->toContain("label: 'Duplicate Detection'")
        ->toContain('Filter admin navigation')
        ->toContain('isNavigationItemActive')
        ->toContain('section.items.length === 1');
});
