<?php

test('admin navigation follows the marketplace module hierarchy', function () {
    $adminLayout = file_get_contents(dirname(__DIR__, 2).'/resources/js/layouts/admin-layout.tsx');

    expect($adminLayout)
        ->toContain("label: 'Dashboard'")
        ->toContain("label: 'Sellers'")
        ->toContain("label: 'Catalog'")
        ->toContain("label: 'Pricing'")
        ->toContain("label: 'Orders'")
        ->toContain("label: 'Inventory'")
        ->toContain("label: 'Warehouses'")
        ->toContain("label: 'Logistics'")
        ->toContain("label: 'Returns & Refunds'")
        ->toContain("label: 'Payments'")
        ->toContain("label: 'Customers'")
        ->toContain("label: 'Marketing'")
        ->toContain("label: 'Reviews'")
        ->toContain("label: 'Support'")
        ->toContain("label: 'Analytics'")
        ->toContain("label: 'Settings'")
        ->toContain("label: 'Overview'")
        ->toContain("label: 'Today’s Orders'")
        ->toContain("label: 'Revenue'")
        ->toContain("label: 'Active Sellers'")
        ->toContain("label: 'Pending Approvals'")
        ->toContain("label: 'Returns'")
        ->toContain("label: 'Low Stock'")
        ->toContain("label: 'Fulfilment'")
        ->toContain("label: 'Activity'")
        ->toContain("label: 'Seller List'")
        ->toContain("label: 'New Seller'")
        ->toContain("label: 'Applications'")
        ->toContain("label: 'KYC Review'")
        ->toContain("label: 'Seller Status'")
        ->toContain("label: 'Documents'")
        ->toContain("label: 'Bank Accounts'")
        ->toContain("label: 'Warehouses'")
        ->toContain("label: 'Performance'")
        ->toContain("label: 'Violations'")
        ->toContain("label: 'Agreements'")
        ->toContain("label: 'Plans'")
        ->toContain("label: 'Products'")
        ->toContain("label: 'New Product'")
        ->toContain("label: 'Listing Requests'")
        ->toContain("label: 'Listing Status'")
        ->toContain("label: 'Quality Review'")
        ->toContain("label: 'Moderation'")
        ->toContain("label: 'Categories'")
        ->toContain("label: 'Brands'")
        ->toContain("label: 'Attributes'")
        ->toContain("label: 'Variants'")
        ->toContain("label: 'Specifications'")
        ->toContain("label: 'Media'")
        ->toContain("label: 'Bundles'")
        ->toContain("label: 'Bulk Upload'")
        ->toContain("label: 'Import & Export'")
        ->toContain("label: 'Duplicates'")
        ->toContain('Filter admin navigation')
        ->toContain('isNavigationItemActive')
        ->toContain('section.items.length === 1');
});
